version: "3.9"
services:
  go:
    build:
      context: .
      dockerfile: Dockerfile.go.dev
    ports:
      - "8081:8081"
    volumes:
      - ./:/app
    networks:
      - server-network
  vue:
    build:
      context: .
      dockerfile: Dockerfile.vue.dev
    ports:
      - "8080:8080"
    volumes:
      - ./www:/www
      - /www/node_modules
    networks:
      - server-network
    environment:
      VUE_APP_API_HOST: "localhost:8081"

networks:
  server-network:
    driver: bridge

