FROM golang:1.16-alpine
WORKDIR /app
COPY go.mod .
COPY go.sum .
RUN go mod download
RUN go install github.com/cespare/reflex@latest
COPY . .
RUN apk add build-base
CMD reflex -s -r '\.go$$' -R www go run main.go
