version: '3'

services:

  go_game:
    container_name: go_game
    image: jysim3/go-game:latest
    expose:
    - "8081"
    networks:
      - mywebsite_server-network
networks:
        mywebsite_server-network:
                external: true
